#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -n cloudy $(id -nu $PGID)
usermod -l cloudy $(id -nu $PUID)

chown -R cloudy:cloudy /app
chown -R cloudy:cloudy /config
chown -R cloudy:cloudy /defaults

echo 'cloudy ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/extra
