#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -n cloudy $(id -nu $PGID)
usermod -l cloudy $(id -nu $PUID)

chown cloudy:cloudy /app
chown cloudy:cloudy /config
chown cloudy:cloudy /defaults
