#!/usr/bin/with-contenv bash

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

echo 'export NVM_DIR="$HOME/.nvm"' >> "$HOME/.bashrc"
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> "$HOME/.bashrc"

chown cloudy:cloudy "$HOME/.bashrc"
chown cloudy:cloudy -R "$HOME/.nvm"

# install local node:14
sudo su cloudy
source "$HOME/.bashrc"
nvm install 14
sudo su root

chown cloudy:cloudy "$HOME/.bashrc"
chown cloudy:cloudy -R "$HOME/.nvm"
